cmake_minimum_required(VERSION 3.5)
project(orbslam3_ros2)

# You should set the PYTHONPATH to your own python site-packages path
# set(ENV{PYTHONPATH} "/opt/ros/jazzy/lib/python3.12/site-packages")

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/CMakeModules)

# Default to C++14
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
endif()

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_components REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(cv_bridge REQUIRED)
find_package(message_filters REQUIRED)
find_package(Sophus REQUIRED)
find_package(Pangolin REQUIRED)
find_package(ORB_SLAM3 REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(tf2_geometry_msgs REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(std_srvs REQUIRED)
find_package(orbslam3_msgs REQUIRED)

# ensure message include paths pulled in automatically


include_directories(
  include
  ${ORB_SLAM3_ROOT_DIR}/include
  ${ORB_SLAM3_ROOT_DIR}/include/CameraModels
  ${ORB_SLAM3_ROOT_DIR}/Thirdparty/Sophus
)

link_directories(
  include
)

# add_executable(mono  src/mono.cpp  src/slam_node.cc)
add_library(mono_component SHARED src/mono.cpp src/slam_node.cc)
ament_target_dependencies(mono_component rclcpp rclcpp_components sensor_msgs cv_bridge ORB_SLAM3 Pangolin OpenCV tf2_geometry_msgs tf2_ros nav_msgs std_srvs orbslam3_msgs)
target_link_libraries(mono_component ${ORB_SLAM3_LIBRARIES} ${Pangolin_LIBRARIES} ${OpenCV_LIBS} ${Sophus_LIBRARIES})
rclcpp_components_register_node(mono_component PLUGIN "orbslam3_ros2::MonocularSlamNode" EXECUTABLE mono-node)

# add_executable(mono-inertial  src/mono-inertial.cpp  src/slam_node.cc)
add_library(mono_inertial_component SHARED src/mono-inertial.cpp src/slam_node.cc)
ament_target_dependencies(mono_inertial_component rclcpp rclcpp_components sensor_msgs cv_bridge ORB_SLAM3 Pangolin OpenCV tf2_geometry_msgs tf2_ros nav_msgs std_srvs orbslam3_msgs)
target_link_libraries(mono_inertial_component ${ORB_SLAM3_LIBRARIES} ${Pangolin_LIBRARIES} ${OpenCV_LIBS} ${Sophus_LIBRARIES})
rclcpp_components_register_node(mono_inertial_component PLUGIN "orbslam3_ros2::MonoInertialNode" EXECUTABLE mono-inertial-node)

# add_executable(mono-compressed  src/mono-compressed.cpp  src/slam_node.cc)
add_library(mono_compressed_component SHARED src/mono-compressed.cpp src/slam_node.cc)
ament_target_dependencies(mono_compressed_component rclcpp rclcpp_components sensor_msgs cv_bridge ORB_SLAM3 Pangolin OpenCV tf2_geometry_msgs tf2_ros nav_msgs std_srvs orbslam3_msgs)
target_link_libraries(mono_compressed_component ${ORB_SLAM3_LIBRARIES} ${Pangolin_LIBRARIES} ${OpenCV_LIBS} ${Sophus_LIBRARIES})
rclcpp_components_register_node(mono_compressed_component PLUGIN "orbslam3_ros2::MonocularCompressedSlamNode" EXECUTABLE mono-compressed-node)

# add_executable(mono-inertial-compressed  src/mono-inertial-compressed.cpp  src/slam_node.cc)
add_library(mono_inertial_compressed_component SHARED src/mono-inertial-compressed.cpp src/slam_node.cc)
ament_target_dependencies(mono_inertial_compressed_component rclcpp rclcpp_components sensor_msgs cv_bridge ORB_SLAM3 Pangolin OpenCV tf2_geometry_msgs tf2_ros nav_msgs std_srvs orbslam3_msgs)
target_link_libraries(mono_inertial_compressed_component ${ORB_SLAM3_LIBRARIES} ${Pangolin_LIBRARIES} ${OpenCV_LIBS} ${Sophus_LIBRARIES})
rclcpp_components_register_node(mono_inertial_compressed_component PLUGIN "orbslam3_ros2::MonoInertialCompressedNode" EXECUTABLE mono-inertial-compressed-node)

add_library(stereo_slam_component SHARED src/stereo.cpp src/slam_node.cc)
ament_target_dependencies(stereo_slam_component rclcpp rclcpp_components sensor_msgs cv_bridge message_filters tf2_geometry_msgs tf2_ros nav_msgs std_srvs orbslam3_msgs ORB_SLAM3 Pangolin OpenCV)
target_link_libraries(stereo_slam_component ${ORB_SLAM3_LIBRARIES} ${Pangolin_LIBRARIES} ${OpenCV_LIBS} ${Sophus_LIBRARIES})
rclcpp_components_register_node(stereo_slam_component PLUGIN "orbslam3_ros2::StereoSlamNode" EXECUTABLE stereo-node)

add_library(stereo_inertial_slam_component SHARED src/stereo_inertial.cpp src/slam_node.cc)
ament_target_dependencies(stereo_inertial_slam_component rclcpp rclcpp_components sensor_msgs cv_bridge message_filters tf2_geometry_msgs tf2_ros nav_msgs std_srvs orbslam3_msgs ORB_SLAM3 Pangolin OpenCV)
target_link_libraries(stereo_inertial_slam_component ${ORB_SLAM3_LIBRARIES} ${Pangolin_LIBRARIES} ${OpenCV_LIBS} ${Sophus_LIBRARIES})
rclcpp_components_register_node(stereo_inertial_slam_component  PLUGIN "orbslam3_ros2::StereoInertialSlamNode"   EXECUTABLE stereo-inertial-node)

add_library(stereo_saver_component SHARED src/stereo_image_saver.cpp)
ament_target_dependencies(stereo_saver_component rclcpp rclcpp_components cv_bridge sensor_msgs message_filters nav_msgs std_srvs ORB_SLAM3 Pangolin OpenCV)
target_link_libraries(stereo_saver_component ${OpenCV_LIBS})
rclcpp_components_register_node(stereo_saver_component PLUGIN "slam::ImageSaver" EXECUTABLE stereo-saver-node)

# 1. Instalar as bibliotecas dos componentes (ESSENCIAL para o Launch achar)
install(TARGETS 
  mono_component
  mono_inertial_component
  mono_compressed_component
  mono_inertial_compressed_component
  stereo_slam_component 
  stereo_inertial_slam_component
  stereo_saver_component
  ARCHIVE DESTINATION lib
  LIBRARY DESTINATION lib
  RUNTIME DESTINATION bin
)
# Install Python scripts
install(PROGRAMS
  scripts/mavlink_bridge_node.py
  DESTINATION lib/${PROJECT_NAME}
)
# install(TARGETS mono mono-inertial mono-compressed mono-inertial-compressed DESTINATION lib/${PROJECT_NAME})
# Install launch files.
install(DIRECTORY launch config vocabulary
 DESTINATION share/${PROJECT_NAME}/)

ament_package()

